import os, json, time, pathlib, subprocess

ROOT = pathlib.Path(r"C:\Users\Thinkpad\Desktop\KonstanceAI")
GEN = ROOT / "scripts" / "generated"
LOGS = ROOT / "logs"
DB = ROOT / "data" / "scripts.json"


def now_ts():
    return int(time.time())


def load_db():
    try:
        raw = DB.read_text(encoding="utf-8-sig") if DB.exists() else ""
        return json.loads(raw) if raw.strip() else {"scripts": []}
    except Exception:
        return {"scripts": []}


def save_db(db):
    DB.write_text(json.dumps(db, indent=2), encoding="utf-8")


def safe_name(name: str):
    keep = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
    out = "".join([c for c in name if c in keep]).strip("_")
    return out[:40] if out else "script"


def create_script(name, purpose):
    db = load_db()
    n = safe_name(name)
    path = GEN / f"{n}.py"

    if path.exists():
        return False, f"Script already exists: {path.name}"

    content = f'''"""
{name} - generated by Konstance Script Factory
Purpose: {purpose}
"""

import argparse
from datetime import datetime


def main():
    parser = argparse.ArgumentParser(description="{purpose}")
    parser.add_argument("--input", default="", help="optional input")
    args = parser.parse_args()

    print("[{name}] running at", datetime.now().isoformat())
    if args.input:
        print("input:", args.input)
    print("TODO: implement script logic")


if __name__ == "__main__":
    main()
'''
    path.write_text(content, encoding="utf-8")

    item = {
        "name": n,
        "file": str(path),
        "purpose": purpose,
        "created_at": now_ts(),
        "last_run_at": None,
        "runs": 0,
        "enabled": True
    }
    db["scripts"].append(item)
    save_db(db)
    return True, f"Created: {path.name}"


def list_scripts():
    db = load_db()
    return db.get("scripts", [])


def get_script(name):
    db = load_db()
    n = safe_name(name).lower()
    for s in db.get("scripts", []):
        if s.get("name", "").lower() == n:
            return db, s
    return db, None


def run_script(name, input_text=""):
    db, s = get_script(name)
    if not s:
        return False, f"Script not found: {name}"
    if not s.get("enabled", True):
        return False, f"Script disabled: {name}"

    path = pathlib.Path(s["file"])
    if not path.exists():
        return False, f"Missing file: {path}"

    # compile gate
    c = subprocess.run(["python", "-m", "py_compile", str(path)], capture_output=True, text=True)
    if c.returncode != 0:
        return False, "Compile failed:\n" + (c.stderr or c.stdout)

    cmd = ["python", str(path)]
    if input_text.strip():
        cmd += ["--input", input_text.strip()]

    r = subprocess.run(cmd, capture_output=True, text=True)
    out = (r.stdout or "").strip()
    err = (r.stderr or "").strip()

    log_path = LOGS / f"script-{s['name']}-{now_ts()}.log"
    log_path.write_text(f"CMD: {' '.join(cmd)}\n\nSTDOUT:\n{out}\n\nSTDERR:\n{err}\n", encoding="utf-8")

    s["last_run_at"] = now_ts()
    s["runs"] = int(s.get("runs", 0)) + 1
    save_db(db)

    if r.returncode != 0:
        return False, f"Run failed. Log: {log_path.name}\n{err[:800]}"

    preview = out[:1200] if out else "(no stdout)"
    return True, f"Run ok OK Log: {log_path.name}\n{preview}"


def usage():
    print("Usage:")
    print("  python scripts/script_factory.py create <name> <purpose>")
    print("  python scripts/script_factory.py list")
    print("  python scripts/script_factory.py run <name> [input_text]")


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        usage(); raise SystemExit(1)

    cmd = sys.argv[1].lower()

    if cmd == "create":
        if len(sys.argv) < 4:
            usage(); raise SystemExit(1)
        ok, msg = create_script(sys.argv[2], " ".join(sys.argv[3:]).strip())
        print(msg); raise SystemExit(0 if ok else 2)

    if cmd == "list":
        items = list_scripts()
        if not items:
            print("No scripts yet.")
        else:
            for s in items:
                print(f"- {s['name']} | runs={s.get('runs',0)} | enabled={s.get('enabled',True)}")
        raise SystemExit(0)

    if cmd == "run":
        if len(sys.argv) < 3:
            usage(); raise SystemExit(1)
        name = sys.argv[2]
        inp = " ".join(sys.argv[3:]).strip() if len(sys.argv) > 3 else ""
        ok, msg = run_script(name, inp)
        print(msg); raise SystemExit(0 if ok else 3)

    usage(); raise SystemExit(1)

